#!/bin/bash
# start the scanning process via clamav
set -e
URI="$1"
TMPMNT=$(mktemp -d)
TMPIMAGE=$(mktemp -u)

cleanup() {
    echo "cleanup"
    umount "$TMPMNT"
}

trap cleanup EXIT

qemu-img create -b "$URI" -f qcow2 -F raw "${TMPIMAGE}.qcow2"
guestmount -o allow_other --format=raw --ro -ia "$TMPIMAGE.qcow2" "$TMPMNT"
echo "mounted"
echo "running scan"
docker run -v /tmp:/tmp clamav/clamav clamscan -ir "$TMPMNT"
